# SAM CLI configuration file
version = 0.1

[default]
[default.global]
[default.global.parameters]
region = "us-east-1"
confirm_changeset = false
fail_on_empty_changeset = false
show_diff_context = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Environment-specific configurations
[dev]
[dev.global]
[dev.global.parameters]
region = "us-east-1"
stack_name = "book-library-api-dev"

[dev.deploy]
[dev.deploy.parameters]
stack_name = "book-library-api-dev"
parameter_overrides = [
  "Environment=dev",
  "AllowedOrigins=*",
  "RateLimitPerMinute=100",
  "EnableWAF=false",
  "EnableCustomDomain=false",
  "EnableXRay=false"
]

[staging]
[staging.global]
[staging.global.parameters]
region = "us-east-1" 
stack_name = "book-library-api-staging"

[staging.deploy]
[staging.deploy.parameters]
stack_name = "book-library-api-staging"
parameter_overrides = [
  "Environment=staging",
  "AllowedOrigins=https://*.staging.booklibrary.com",
  "RateLimitPerMinute=200",
  "EnableWAF=true",
  "EnableCustomDomain=false",
  "EnableXRay=true",
  "ReservedConcurrentExecutions=50"
]

[production]
[production.global]
[production.global.parameters]
region = "us-east-1"
stack_name = "book-library-api-production"

[production.deploy]
[production.deploy.parameters]
stack_name = "book-library-api-production"
parameter_overrides = [
  "Environment=production",
  "AllowedOrigins=https://booklibrary.com,https://www.booklibrary.com",
  "RateLimitPerMinute=1000",
  "EnableWAF=true",
  "EnableCustomDomain=true",
  "CustomDomainName=api.booklibrary.com",
  "EnableXRay=true",
  "ReservedConcurrentExecutions=100",
  "ProvisionedConcurrentExecutions=10"
]